title: Suket Shah's Website
author: Suket Shah
email: skshah@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This website is for an APCS project that is due on June 12, 2020. I have to include my name, picture, social media information, and my brag sheet.

# social links
twitter_username: suketshah3
github_username:  suketshah7

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
